image_root: "data/Flickr8k/images"
ann_root: "data/Flickr8k/annotations"
coco_gt_root: "annotation/coco_gt"

# 학습, 검증, 테스트 파일 설정
train_file: "flickr8k_train.json"
val_file: "flickr8k_val.json"
test_file: "flickr8k_test.json" # 필요에 따라 추가

# set pretrained as a file path or an url
pretrained: "checkpoints/blip_smile_base.pth"

# size of vit model; base or large
vit: "base"
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 16
init_lr: 1e-5

# vit: 'large'
# vit_grad_ckpt: True
# vit_ckpt_layer: 5
# batch_size: 16
# init_lr: 2e-6

image_size: 384

# generation configs
max_length: 75
min_length: 1
num_beams: 3
prompt: "a picture of "

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 5
